# Generated by Django 6.0 on 2026-08-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='import_price',
            new_name='gia_ban',
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='sale_price',
            new_name='gia_nhap',
        ),
    ]
