# Generated by Django 6.0 on 2026-08-06 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_nguoi_mat', models.CharField(max_length=25)),
                ('nq', models.CharField(blank=True, max_length=50, null=True)),
                ('ngay', models.CharField(blank=True, max_length=2, null=True)),
                ('thang', models.CharField(blank=True, max_length=2, null=True)),
                ('nam', models.CharField(blank=True, max_length=4, null=True)),
                ('dt_kho', models.CharField(blank=True, max_length=15, null=True)),
                ('tong_tien_ban', models.PositiveIntegerField(default=0)),
                ('tong_tien_nhap', models.PositiveIntegerField(default=0)),
                ('tong_tien_lai', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='btl.user')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('gia_ban_thuc_te', models.PositiveIntegerField()),
                ('gia_nhap_thuc_te', models.PositiveIntegerField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='btl.contract')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='btl.inventoryitem')),
            ],
        ),
    ]
