# Generated by Django 6.0 on 2026-08-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward_Penalty',
            fields=[
                ('reward_penalty_id', models.AutoField(primary_key=True, serialize=False)),
                ('so_lan_di_muon', models.IntegerField()),
                ('so_lan_bi_phan_anh', models.IntegerField()),
                ('so_lan_tip', models.IntegerField()),
                ('tien_thuong_phat', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='import_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sale_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
